### ISSUE TITLE
TYPO3 v9: Invalid argument supplied for foreach() in [...]NamespaceDetectionTemplateProcessor.php line 180

### ISSUE THREAD

**Issue by vertexvaar** [in2code-de/lux#5] opened 2019-07-06 11:03 UTC
Hi,

i installed lux via composer in a freshly set up TYPO3 environment (`composer require typo3/minimal`).
Opening the "Analysis" or "Leads" module leads to teh following exception:

```
PHP Warning: Invalid argument supplied for foreach() in [...]/www/vendor/typo3fluid/fluid/src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php line 180
```

**Comment by einpraegsam** [comment] 2019-07-06 12:39
I tried to reproduce it but I was not able to see the error.
Installed typo3/minimal with 9.5 and latest lux (and typo3-console). After a db compare everything looks like it should in backend. 
Any more information?

**Comment by vertexvaar** [comment] 2019-07-07 12:31
composer.json and lock file are attached.

What might be interesting for you: The default setting `[SYS][exceptionalErrors] = 12290`

I tried it again. Freshly installed typo3 minimal, created the empty start page during setup. Including the TypoScript does not change anything.

[composer.zip](https://github.com/in2code-de/lux/files/3365623/composer.zip)

```
TYPO3 Version	9.5.8
Webserver	Apache/2.4.39 (Unix) OpenSSL/1.1.1b
PHP Version	7.3.5
Database (Default)	MySQL 5.7.25
Application Context	Development/Docker
Composer mode	Enabled
Operating System	Linux 5.0.0-20-generic
```
![Screenshot from 2019-07-07 14-29-45](https://user-images.githubusercontent.com/5594393/60768383-afcc9d00-a0c3-11e9-9784-13ba38b13da6.png)

**Comment by einpraegsam** [comment] 2019-07-07 13:24
ok, turned exceptionalErrors to 12290, used your composer.lock and did a composer install. 
I'm not able to run into that issue.
Same TYPO3 version (of course because of composer.lock), but PHP 7.2 and MySQL 5.7.26.

**Comment by waue** [comment] 2019-07-11 12:39
I can confirm that this warning only appears in PHP 7.3. PHP 7.2 works fine

**Comment by einpraegsam** [comment] 2019-07-11 13:16
ok, will test again with 7.3

**Comment by einpraegsam** [comment] 2019-07-12 22:01
Ths for pointing me to this issue. For whatever reason it's not possible any more to use inline JS in Fluid in PHP 7.3. I extracted everything to files now.
Will be fixed in the upcoming version of lux.

**Closed by einpraegsam** 2019-07-12 22:01 UTC
Labels: question

**Comment by einpraegsam** [comment] 2019-07-12 22:06
4.1.1 just released with this fix
